### PR TITLE
feat: sort TemperaturePresets

### PR DESCRIPTION
**Pull request by jnimety**
Sort Temperature presets in UI Settings and Dashboard Thermals Widget

Signed-off-by: Joel Nimety <jnimety@gmail.com>

### CODE REVIEW

**Comment by cadriel** [comment]
I haven't forgotten about this - but am in the middle of a large refactor of this data. Will have a chat once I've got that in place, as it likely changes a lot to do with this PR.

**Comment by cadriel** [comment]
Hi,

I have merged the refactor into develop - can you please rebase this on to develop, and I'll get it merged. Thanks!

**Comment by jnimety** [comment]
rebased. My pi and printer are down at the moment so I did not test yet. I will do that later this weekend unless you get to it first.

**Comment by cadriel** [comment]
Thanks, this looked good.

**Pull request merged**
