### PR TITLE
Add i18n, Chinese language support

### PR DESCRIPTION
**Pull request by QABQ**
completed:
1.Add i18n plugin
2.Add Chinese/English language pack
3.English language by default

to do list:
1.You need to add a language switch button at a suitable location, and realize language switch by controlling "localStorage lang"

img:
image
image
image
image
image

### CODE REVIEW

**Comment by QABQ** [comment]
@cadriel  Do you have any suggestions?

**Comment by cadriel** [comment]
Yep, at first glance this is looking really good. I'll need some time to review this tho - as I think there were others also working on similar functionality.

Also - would you be able to clean up the branch a little? Merging develop -> develop can create a messy tree. Perhaps move it to a branch, squash it all and rebase?

**Comment by QABQ** [comment]
> 是的，乍一看，这看起来真的很好。我需要一些时间来回顾这个问题-因为我认为还有其他人也在研究类似的功能。
> 
> 另外-您能稍微清理一下分支吗？合并开发->开发可以创建一棵凌乱的树。也许将其移至分支，将其全部压榨并重新定座？

Ok, I can also add the Chinese language pack to the internationalization module after it is stable. Before that, I will sort out my code and submit it

**Comment by QABQ** [comment]
> Yep, at first glance this is looking really good. I'll need some time to review this tho - as I think there were others also working on similar functionality.
> 
> Also - would you be able to clean up the branch a little? Merging develop -> develop can create a messy tree. Perhaps move it to a branch, squash it all and rebase?

Ok, I can also add the Chinese language pack to the internationalization module after it is stable. Before that, I will sort out my code and submit

**Pull request closed without merging**
