### PR TITLE
feature(gcode-preview): Add G-code preview card

### LINKED ISSUE #181: GCODE preview
A gcode preview like octoprint has would be very usefull, especially if it can sync up to the current print

### PR DESCRIPTION
**Pull request by Mechazawa**
It still needs some work before it can be merged but I feel it's ready for some feedback, closes #181 

https://user-images.githubusercontent.com/1144171/115975397-c24beb00-a564-11eb-91dd-8d4dfb70bbf1.mp4

https://user-images.githubusercontent.com/1144171/115975401-c7a93580-a564-11eb-84c4-4bf65116e0a9.mp4

### CODE REVIEW

**Comment by Mechazawa** [comment]
Nightly builds of this branch are pushed to https://hub.docker.com/repository/docker/mechazawa/fluidd

**Comment by cadriel** [comment]
Hey, thanks so much - this is 100% a very much wanted feature. I'll try to dedicate some time to review this a bit later today.

**Comment by cadriel** [comment]
So - some initial thoughts;

- First, really impressed. There's a lot going on here, and I appreciate the effort to get some well thought out settings in place - along with how you've implemented the preview alongside the file system etc.
- What is your intent with auto-loading here? Perhaps an option users can toggle so they're;
  - not forced to use the feature, if say they're on a lower powered device etc - or for those that have no use of it. I.e., maybe an option on the settings page that disables the feature, that perhaps disables the same data flag as if you'd disable it in layout mode.
  - and an option to toggle auto loading the file on print start
- Secondly, i'm getting a bunch of console errors - and it seems like its not loading my gcodes properly. Some screenshots attached as reference.

The errors kind of halted my progress a bit, so if you could resolve those or point me in the right direction - that'd be great. It might simply be some missing dependencies, unsure. I did make sure to `npm i` prior to startup.

First load of app;
Screen Shot 2021-04-25 at 3 35 31 PM

Attempted load of a gcode;
Screen Shot 2021-04-25 at 3 35 50 PM

Started adjusting layer count and progress;
Screen Shot 2021-04-25 at 3 36 07 PM

Looking forward to testing some more.

Cheers!

**Comment by Mechazawa** [comment]
>    * First, really impressed. There's a lot going on here, and I appreciate the effort to get some well thought out settings in place - along with how you've implemented the preview alongside the file system etc.

Thanks!

>    * What is your intent with auto-loading here? Perhaps an option users can toggle so they're;

What do you mean by auto-loading? For loading the current print I was planning on adding a dedicated button to the controls section of the gcode preview card.

>   * Secondly, i'm getting a bunch of console errors - and it seems like its not loading my gcodes properly. Some screenshots attached as reference.

I think something is going wrong while it's parsing gcode parameters. Could you upload some gcode that breaks the viewer so I can debug this locally?

**Comment by cadriel** [comment]
Both of these caused issues for me in one way or another.

[KVP_T-RexSkull_Jaw-4h16m.zip](https://github.com/cadriel/fluidd/files/6373487/KVP_T-RexSkull_Jaw-4h16m.zip)
[voron-quick-print-2m.zip](https://github.com/cadriel/fluidd/files/6373488/voron-quick-print-2m.zip)

**Comment by Mechazawa** [comment]
Fixed the bug that you were encoutering that was generating faulty SVG paths

**Comment by cadriel** [comment]
This is working much better.

A couple of changes;

- Can you adjust the visual aesthetic of the preview, perhaps darken the white border on selection etc. I believe in light mode this is blue too, so needs adjusting there as well.
- All labels / text need translation entries. I can add these if you're not familiar with this.. let me know.
- When adjusting browser size - the object tends to scroll off in a weird way. It's not major, but if it's something we can fix it'd be nice.
- Are the extrusion and retraction checkboxes working properly? I can't see much of a visual change when toggling the retractions.. and when toggling the extrusion it essentially removes the layer.

Thanks!

**Comment by cadriel** [comment]
Out of interest, I assume the layer count once parsed accounts for variable layer heights too, right?

**Comment by cadriel** [comment]
Also - may need to look into resolving performance. I notice when I zoom into a plate, things get slow. Currently testing with a full plate at about 68MB.

**Comment by cadriel** [comment]
> I did some already and I'm planning on doing the rest today. Should I also try to translate it to the other languages or should just English be fine?

Just english is fine, other translators will come along and update these.

> Could you send me the file for testing? Are you using an integrated or dedicated GPU?

I'm using a '19 macbook pro, using the dedicated GPU which is a Radeon Pro 560X 4 GB.

Attached the example gcode, and a quick movie to illustrate.

I imagine others have much larger gcodes too;

[KVP blower housing_rear-179.605g-17h9m.gcode.zip](https://github.com/cadriel/fluidd/files/6380481/KVP.blower.housing_rear-179.605g-17h9m.gcode.zip)


https://user-images.githubusercontent.com/205520/116155014-24b10280-a6af-11eb-8307-3467aa7a5468.mov

**Comment by cadriel** [comment]
Noticed some commits - note, bed size can be pulled from the config in memory. I think in the future, to implement cancel object - it might be nice if the viewer represented the actual bed size.

Also, my other machines don't show as much slowdown as my mac. Will have a few more testers on this soon too - so will pass along feedback.

Feel free to join the Fluidd discord if you'd like to chat too! :)

**Comment by cadriel** [comment]
Screen Shot 2021-05-03 at 4 20 08 PM

Is this expected? I assume its because i'm loading a gcode for a bed that's larger.

**Comment by cadriel** [comment]
A couple of questions;

- Did you manage to get the throttle in place?
-

**Comment by cadriel** [comment]
- Can you squash as necessary, and rebase on develop?
- I notice cancelling the preview before its downloaded / parsed is a bit broken - but so is the file edit dialog. I think we can fix this after merge.
- Did you manage to get the throttle in place for the sliders?

**Comment by Mechazawa** [comment]
> Screen Shot 2021-05-03 at 4 20 08 PM
> 
> Is this expected? I assume its because i'm loading a gcode for a bed that's larger.
Yeah, I make sure that the bed size is still the size I get from the config to show the user that the print probably isn't going to fit

**Comment by Mechazawa** [comment]
>     * Can you squash as necessary, and rebase on develop?

Will do that tonight

>     * I notice cancelling the preview before its downloaded / parsed is a bit broken - but so is the file edit dialog. I think we can fix this after merge.
> 
>     * Did you manage to get the throttle in place for the sliders?

**Comment by cadriel** [comment]
I messed with this, and didn't want to push the squash to your branch - so i've merged it my side.  Commit still exists under your name, hope this is good. :)

Closing - as now merged.

**Comment by rizwansarwar** [comment]
So how does one enable it? I updated to latest release which seem to have gcode preview, but I can't see a way to show it in my browser. Is there something special I need to do?

**Comment by cadriel** [comment]
gcode-preview is not currently enabled.

**Comment by rizwansarwar** [comment]
Ok, any plans on GA soon? Not complaining, just want to test it as I use it in Octoprint and wanted to see for comparison purposes.

**Comment by kieraneglin** [comment]
Is there a way to enable this or set Fluidd to automatically use betas/nightlies?  I'd love to test this feature out!

**Comment by cadriel** [comment]
I'll consider releasing it as a preview / beta - with an option to toggle it in via settings.

**Comment by burabure** [comment]
can we get this, pretty please?

**Comment by cadriel** [comment]
@burabure This was already released in v1.15.0

**Pull request closed without merging**
