### PR TITLE
feat: Allow multiple files upload from upload button.

### PR DESCRIPTION
**Pull request by shinuza**
This is disabled for "upload & print" button.

### CODE REVIEW

**Comment by cadriel** [comment]
Does this respect the same functionality that the multi-file drag and drop upload achieves? I.e., you see the progress - and each file is uploaded sequentially, not async?

I'll test myself too but otherwise if that all works then it looks good! Nice work.

**Comment by shinuza** [comment]
Sure, I just came across that comment in FileSystemCard.vue, will do.

**Comment by cadriel** [comment]
Just tested - it uploads async at the moment, and that's potentially a problem. Need to update to make this synchronous, the same as the drag upload.

**Comment by shinuza** [comment]
Just updated it, it works as intended. But I'd love your input on architecture/coding style.

**Comment by cadriel** [comment]
Great work! Thanks!

**Pull request merged**
