### PR TITLE
Add Firmware Retraction card.

### PR DESCRIPTION
**Pull request by yadotrof**
image
My JS code may look ugly because I never worked with him before.
This PR can be reviewed only as an idea, but if anyone can advise me on how to improve code I'll do my best.

### CODE REVIEW

**Comment by cadriel** [comment]
This looks like a great start. Here's some comments;

- I'm wondering if this shouldn't exist on the tune page instead. Happy to talk about this.
- The card should only be displayed if firmware retractions are turned on. This value should exist in `store.printer.printer.fileconfig.settings`

If you're happy with where this is, I can merge and adjust as needed. Thank you for the contribution!

**Comment by yadotrof** [comment]
> I'm wondering if this shouldn't exist on the tune page instead

In my opinion, the retract configuration is a common printing procedure such as speed and temperature configuration. And often it needs to be adjusted at the time of printing.
So I think it should be presented in the dashboard.

The main question in this is "What fundamental difference between tune and home page?". Because now "Tune page" == "Bed mesh page".

Cards on the tune page can`t be hidden and the layout can`t be changed. But users may like to hide the retraction card. This is another argument for the dashboard.

> The card should only be displayed if firmware retractions are turned on. This value should exist in store.printer.printer.fileconfig.settings

Done

OFFTOP:
As retract configuration depends on the filament type, maybe it would be nice to have presets for this setting in the future.

**Comment by cadriel** [comment]
This is looking good! Thanks.

I'll get this merged soon.

**Comment by cadriel** [comment]
Merged, thank you!

**Pull request merged**
