### PR TITLE
Update index.ts

### PR DESCRIPTION
**Pull request by CodingJustForRun**
Adding hungarian language to initial main menu, and for equality reordered the language names by label order, leaving english as first/default. I hope noone got offended by my actions.
Love and cheers.

### CODE REVIEW

**Comment by shinuza** [comment]
Thank you but this will be added in the other PR

**Comment by cadriel** [comment]
I merged the other PR, which didn't include these changes.

What's the intent here, merge this or wait for another PR?

**Comment by shinuza** [comment]
@cadriel I was gonna ask you if there was a way for me to edit the PR and add this change. @CodingJustForRun is not super confortable with git.  If you are ok with the re-ordering of the keys I can to that in another PR I'm prepping that adds Korean

**Comment by shinuza** [comment]
PR created: https://github.com/cadriel/fluidd/pull/219

**Comment by cadriel** [comment]
Sweet, I'll close this and merge the other.

Thanks!

**Pull request closed without merging**
